board/urls.py
from unicodedata import name
from django.urls import path
from . import views

app_name = 'board'

urlpatterns = [
    path('index/', views.index, name='index'),
    path('post/', views.post, name='post'),
    path('cancel/', views.cancel, name='cancel'),
    path('post/<int:id>', views.detail, name='detail'),
    path('post/<int:id>/delete', views.board_delete, name='board_delete'),
    path('main/', views.main, name='main'),
    path('post/<int:id>/edit/', views.board_edit, name='board_edit'),
]

config/urls.py
from xml.etree.ElementInclude import include
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    # member urls
    path('admin/', admin.site.urls),
    path('member/', include('member.urls')),

    # board urls
    path('', include('board.urls')),
    path('admin/', admin.site.urls),
    
    # chat urls
    path('chat/', include('chat.urls')),
    
    #gps urls
    path('gps/', include('gps.urls')),
]

gps/urls.py
from xml.etree.ElementInclude import include
from django.urls import path
from . import views

urlpatterns = [
    path('shop/', views.shop, name='shop_location'),
] 

member/urls.py
from xml.etree.ElementInclude import include
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings
app_name ='member'
urlpatterns = [
    path('login/', views.signin, name='user_login'),
    path('signup/', views.signup, name='user_signup'),
    path('logout/', views.signout, name='user_logout'),
   
]
# urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

board/models.py
from django.db import models

# Create your models here.


# Create your models here.
class Board(models.Model):
    #board_id = models.IntegerField(primary_key=True)
    id = models.AutoField(primary_key=True)
    author = models.CharField(max_length=10, null=False) # 작성자 이름 
    title = models.CharField(max_length=100, null=False) # 게시판 제목
    content = models.TextField(null=False) # 내용
    created_date = models.DateTimeField(auto_now_add=True) # 게시물 시간
    modified_date = models.DateTimeField(auto_now=True) # 수정된 시간

    #number = models.IntegerField(default=0)
    # image 넣어야하는데....
    
    class Meta:
        db_table = 'board'
        app_label = 'board'

board/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse, HttpResponseRedirect,Http404
from .models import *
from django.urls import reverse
from django.shortcuts import redirect
from django.contrib import messages
from django.core.paginator import Paginator
# Create your views here.

def main(request):
    return render(request,'board/main.html')

# 게시판 목록
def index(request):
    author =request.session.get('login_session', request.user.get_username())
    now_page = int(request.GET.get('page',1))
    boards = Board.objects.order_by('-id')
    p = Paginator(boards,11 )
    info = p.page(now_page) # info = p.get_page(now_page)
    start_page = ((now_page - 1) // 10) * 10 + 1
    end_page = start_page + 9
    if end_page > p.num_pages:
        end_page = p.num_pages
    context = {
    "info":info,
    "boards":boards,
    "author":author,
    'page_range' : range(start_page, end_page + 1)
    }
    return render(request, 'board/list.html', context)

# 게시판 글쓰기
def post(request):
    if request.method == "POST":
        author = request.session['user_id']
        # print(author)
        title = request.POST['title']
        content = request.POST['content']
        # null값이 없어야함
        if author and title and content:
            board = Board(author=author, title=title, content=content)
            board.save()
            return redirect('/index')
        else:
            messages.warning(request,"공란이 없게 해주세요")
            return redirect('/post/')
    else:
        return render(request,'board/post.html')

# 게시판 상세보기 + session
def detail(request, id):
    login_session =request.session.get('login_session', request.user.get_username())
    context = {'login_session':login_session}
    board = get_object_or_404(Board, pk=id)
    context['board'] = board
    print(board.author)
    print(login_session)
    print(context)
    if board.author == login_session:
        context['author'] = True
    else:
        context['author'] = False
    return render(request, 'board/detail.html',context)


# 게시판 삭제
def board_delete(request,id):
    board =get_object_or_404(Board, pk=id)
    board.delete()
    return redirect('/index')

# 게시판 수정
def board_edit(request,id):
    board = Board.objects.get(pk=id)
    if request.method == 'POST':
        board.author = request.session['user_id']
        board.title = request.POST['title']
        board.content = request.POST['content']
        board.board = Board(title=board.title, content=board.content)
        board.save()
        return redirect('/post/'+str(board.id))
    else:
        return render(request,'board/update.html',{'board':board})

def cancel(request,id):
    board = Board.objects.get(pk=id)
    if request.method == "POST":
        return redirect('/index')
    else:
        return render(request,'board/post.html',{"board":board})
    






############### 기존 코드
'''def detail(request, id):
    try:
        board = Board.objects.get(pk=id)
    except Board.DoesNotExist:
        raise Http404("Does not exist!")
    return render(request, 'board/detail.html', {'board': board})'''

board/templates/board/bottom.html
<div class="jumbotron text-center" style="margin-bottom:0px; margin-top:150px">
    <p>AIVLE 4반 1조 MINI_PROJECT</p>
</div>


{% block bottom %}
{% endblock %}

board/templates/board/detail.html
{% load static %}

<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <title>게시판 - {{ board.title }}</title>
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
</head>
<body>
{% include "board/navi_bar.html" %}
{% block content %}
{% endblock %}
<header>
    <div class="navbar navbar-dark bg-dark shadow-sm mb-3">
        <div class="container d-flex justify-content-between">
            <a href="/index/" class="navbar-brand d-flex align-items-center">
                <strong>게시판</strong>
            </a>
        </div>
    </div>
</header>

<div class="container">
    <div class="card">
        <div class="card-body">
            <h5 class="card-title">{{ board.title }} - {{ board.author }}</h5>
            <p class="card-text"><small class="text-muted">{{ board.created_date | date:"Y-m-d h:i" }}</small></p>
            <p class="card-text">{{ board.content }}</p>
        </div>
    </div>
    <div class="row mt-3">
        <div class="col-auto mr-auto"></div>
        {% if author %}
        <div class="col-auto"> 
            <a class="btn btn-info" href="{% url 'board:board_edit' id=board.id %}" role="button">수정</a>
        </div>
        <div class="col-auto">
            <a href = "{% url 'board:board_delete' id=board.id %}" class = "btn btn-info">삭제</a>
        </div>
        <div class="col-auto">
            <a href ="/index/" class="btn btn-info" type="submit" role="button"> 취소</a>
            </div>
        {% else %}
        <div class="col-auto">
            <a href ="/index/" class="btn btn-info" type="submit" role="button"> 취소</a>
            </div>
        {% endif %}
    </div>
</div>
<script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
</body>
</html>

board/templates/board/list.html
{% load static %}

<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <title>게시판 - 목록</title>
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
</head>



<body>
{% include "board/navi_bar.html" %}
{% block content %}
{% endblock %}
    <header>
        <div class="navbar navbar-dark bg-dark shadow-sm mb-3">
            <div class="container d-flex justify-content-between">
                <a href="/index/" class="navbar-brand d-flex align-items-center"><strong> 게시판</strong>
                </a>
            </div>
        </div>
    </header>



    <div>
        {% include "board/side_bar.html" %}
        {% block side %}
        {% endblock %}
    </div>
    <div class="container">
        <table class="table">
            <thead class="thead-light">
            <tr class="text-center">
                <th scope="col">제목</th>
                <th scope="col">내용</th>
                <th scope="col">작성자</th>
                <th scope="col">작성일</th>
            </tr>
            </thead>
            {% comment %} 게시판 출력 {% endcomment %}
            <tbody>
            {% for board in info %}
            <tr class="text-center">
                <td>
                    <span>{{ board.title }}</span>
                </td>
                <td>
                    <a href="/post/{{ board.id }}">
                        <span>{{ board.content }}</span>
                    </a>
                </td>
                <td>
                    <span>{{ board.author }}</span>
                </td>
                <td>
                    <span>{{ board.created_date | date:"Y-m-d h:i" }}</span>
                </td>
            </tr>
            {% endfor %}
            </tbody>
        </table>
        <div style='text-align:center;'>
            <ul class='pagination' style='justify-content: center;''>
            {% for i in page_range %}
            <div style="margin: 5px;">
            <li>
                <a href='{% url "board:index" %}?page={{ i }}'>
                    {{ i }}
                </a>
            </li>
        </div>
            {% endfor %}
            </ul>
    </div>
    {% if author %}
    <div class="row">
        <div class="col-auto mr-auto"></div>
        <div class="col-auto">
            <a class="btn btn-primary" href="/post" role="button">글쓰기</a>
        </div>
    </div>
    {% endif%}
</div>
{% include "board/bottom.html" %}
{% block bottom %}
{% endblock %}
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
</body>
</html>

board/templates/board/main.html
<!DOCTYPE html>
{% load static %}
<html lang="ko">
<head>
  <title>AIVLE 최강4반 통장잔고 1조</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css">
  <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js"></script>
  <style>
  .fakeimg {
    height: 200px;
    background: #aaa;
  }
  .right {
      float right
  }
  </style>
</head>
<body>

<div class="jumbotron text-center" style="margin-bottom:0" href="/main">
  <h1><a href="/main" style="color: #FB7A01;">펫투유</a></h1>
  <br>
  <p>펫투유는 django를 활용하여 회원간의 소통, 주변가게 검색을 목적으로 하는 웹사이트입니다.</p> 
</div>
<nav class="navbar navbar-expand-sm bg-dark navbar-dark">
  <a class="navbar-brand" href="/main">PET_TO_YOU</a>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
    <span class="navbar-toggler-icon"></span>
  </button>
  
  <div class="collapse navbar-collapse" id="collapsibleNavbar">
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" href="../index">게시물 작성</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="../chat">채팅 하기</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="../gps/shop">주변 가게 검색</a>
      </li>
    </ul>
  </div> 

  <div id="collapsibleNavbar">
    <ul class="navbar-nav">
      <li class="nav-item">     
      {% if user.is_authenticated %}
        <p style="display:inline-block; color: white; margin-right: 20px; padding: 0; padding-top: 15px;">{{user.username}} {{session_id}}님 환영합니다</p>          
      </div>            
      <a href="{% url 'member:user_logout' %}" class="n avbar-brand d-flex align-items-center"><strong>로그아웃</strong></a>
      {% else %}
      <a href="{% url 'member:user_login' %}" class="n avbar-brand d-flex align-items-center"><strong>로그인</strong></a>
      {% endif %}
  </li>
    </ul>
  </div>
</nav>
<div style="margin-top:30px">
  {% include "board/side_bar.html" %}
  {% block side %}
  {% endblock %}
</div>
<div class="container" style="margin-top:30px;>
  <!--사이드 바-->
  {% comment %} <div class="row">
    <div class="col-sm-4">
      <ul class="nav nav-pills flex-column">
        <li class="nav-item">
          <a class="nav-link active" href="../main">PET_TO_YOU</a> 
          <!-- 홈 화면으로 -->
        </li>
        <li class="nav-item">
          <a class="nav-link disabled">수도권 4반 1조</a>
          <!-- 반 조이름 -->
        </li>
        <!-- 각 기능별 링크  -->
        <li class="nav-item">
          <a class="nav-link" href="../index">게시물 작성</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="../chat/index">채팅 하기</a>
        </li>
        <li class="nav-item" sfloat:right>
          <a class="nav-link" href="../gps/shop">주변 가게 검색</a>
        </li>
      </ul>
      <hr class="d-sm-none">
    </div> {% endcomment %}
    
    <div class="col-sm-8">
      <h2>로그인, 회원가입</h2>
      <div>
        <img src="{%static 'img/login_image.png' %}" width="830" height="500px">
        <p>Django 내장 기능 사용을 사용하여 사용자의 정보를 DB에 저장합니다.
           DB에 저장 된 data값과 비교하며 로그인 할 수 있습니다.
      </div>

      <br>
      <hr>

      <h2>게시판</h2>
      <div>
        <img src="{%static 'img/board_list_image.png' %}" width="830" height="500px">
        <p>django와 DB를 활용하여 회원정보를 통해서 게시물을 작성하고 수정, 삭제가 가능합니다.</p>
      </div>
      
      <br>
      <hr>

      <h2>채팅</h2>
        <div><img src="{%static 'img/chat_image.png' %}" width="830" height="500px">
        <p>django의 Channel 라이브러리를 통해 WebSocket 프로토콜로 실시간으로 채팅할 수 있습니다.</p>
      </div>

      <br>
      <hr>


      <h2>주변 가게 검색</h2>
      <div>
        <img src="{%static 'img/shop_image.png' %}" width="830" height="500px">
        <p>GeoCoder와 카카오api를 통해 사용자 주소 근방의 가게들을 검색 할 수 있습니다.
      </div>
    </div>
    
    
    
    
  </div>
</div>

<div class="jumbotron text-center" style="margin-bottom:0">
  <p>AIVLE 4반 1조 MINI_PROJECT</p>
</div>

</body>
</html>

board/templates/board/navi_bar.html
<nav class="navbar navbar-expand-sm bg-dark navbar-dark">
  <a class="navbar-brand" href="/main">PET_TO_YOU</a>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
    <span class="navbar-toggler-icon"></span>
  </button>
  
  <div class="collapse navbar-collapse" id="collapsibleNavbar">
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" href="/../index">게시물 작성</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/../chat">채팅 하기</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/../gps/shop">주변 가게 검색</a>
      </li>
    </ul>
  </div> 

  <div id="collapsibleNavbar">
    <ul class="navbar-nav">
      <li class="nav-item">            
      {% if user.is_authenticated %}
        <p style="display:inline-block; color: white; margin-right: 20px; padding: 0; padding-top: 15px;">{{user.username}}님 환영합니다</p>          
      </div>            
      <a href="{% url 'member:user_logout' %}" class="n avbar-brand d-flex align-items-center"><strong>로그아웃</strong></a>
      {% else %}
      <a href="{% url 'member:user_login' %}" class="n avbar-brand d-flex align-items-center"><strong>로그인</strong></a>
      {% endif %}
    </ul>
  </div>
</nav>
{% block content %}
{% endblock %}

board/templates/board/post.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">

<head>
    <meta charset="UTF-8">
    <title>게시판 - 글쓰기</title>
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
</head>

<body>
    {% include "board/navi_bar.html" %}
{% block content %}
{% endblock %}
<header>
    <div class="navbar navbar-dark bg-dark shadow-sm mb-3">
        <div class="container d-flex justify-content-between">
            <a href="/index/" class="navbar-brand d-flex align-items-center">
                <strong>게시판</strong>
                
            </a>
        </div>
    </div>
</header>


<div class="container">
    
    <form action="/post/" method="post">
        {% csrf_token %}
        <div class="form-group row">
            <label for="inputTitle" class="col-sm-2 col-form-label"><strong>제목 </strong></label>
            <div class="col-sm-10">
                <input type="text" name="title" class="form-control" id="inputTitle">
            </div>
        </div>

        <div class="form-group row">

            <label for="inputAuthor" class="col-sm-2 col-form-label" ><strong>작성자</strong></label>

             <div class="col-sm-10">

                <name="author" class="form-control" id="inputAuthor">{{user.username}}

            </div>  

        </div>

        <div class="form-group row">
            <label for="inputContent" class="col-sm-2 col-form-label"><strong>내용</strong></label>
            <div class="col-sm-10">
                <textarea type="text" name="content" class="form-control" id="inputContent"></textarea>
            </div>
        </div>
    
        <div class="row">
            <div class="col-auto mr-auto"></div>
            <div class="col-auto">
                <input class="btn btn-primary" type="submit" role="button" value="글쓰기">
                <a href ="/index/" input class="btn btn-primary" type="submit" role="button"> 취소</a>
 
            </div>
        </div>
    </form>
    
</div>
<script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
{% include "board/bottom.html" %}
{% block bottom %}
{% endblock %}
</body>

</html>

board/templates/board/side_bar.html
<div class="col-sm-2" style="float:left">
  <ul class="nav nav-pills flex-column">
    <li class="nav-item">
      <a class="nav-link active" href="../main">PET_TO_YOU</a> 
      <!-- 홈 화면으로 -->
    </li>
    <li class="nav-item">
      <a class="nav-link disabled">수도권 4반 1조</a>
      <!-- 반 조이름 -->
    </li>
    <!-- 각 기능별 링크  -->
    <li class="nav-item">
      <a class="nav-link" href="/../index">게시물 작성</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="/../chat/index">채팅 하기</a>
    </li>
    <li class="nav-item" sfloat:right>
      <a class="nav-link" href="/../gps/shop">주변 가게 검색</a>
    </li>
  </ul>
  <hr class="d-sm-none">
</div>
{% block side %}
{% endblock %}

board/templates/board/update.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">

<head>
    <meta charset="UTF-8">
    <title>게시판 - 글쓰기</title>
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
</head>

<body>
<header>
    <div class="navbar navbar-dark bg-dark shadow-sm mb-3">
        <div class="container d-flex justify-content-between">
            <a href="/index/" class="navbar-brand d-flex align-items-center">
                <strong>게시판</strong>
            </a>
        </div>
    </div>
</header>

{% include "board/side_bar.html" %}
{% block side %}
{% endblock %}

<div class="container">
    <form action="{% url 'board:board_edit' board.id %}" method="post">
        {% csrf_token %}
        <div class="form-group row">
            <label for="inputTitle" class="col-sm-2 col-form-label"><strong>제목</strong></label>
            <div class="col-sm-10">
                <input type="text" name="title" class="form-control" id="inputTitle" value={{board.title}}>
            </div>
        </div>

        <div class="form-group row">
            <label for="inputAuthor" class="col-sm-2 col-form-label" ><strong>작성자</strong></label>
             <div class="col-sm-10">
                <name="author" class="form-control" id="inputAuthor">{{board.author}}
            </div>  
        </div>

        <div class="form-group row">
            <label for="inputContent" class="col-sm-2 col-form-label"><strong>내용</strong></label>
            <div class="col-sm-10">
                <input type="text" name="content" class="form-control" id="inputContent" value={{board.content}}>
            </div>
        </div>
        <div class="row">
            <div class="col-auto mr-auto"></div>
            <div class="col-auto">
                <button class="btn btn-primary"  type="submit" role="button">수정하기</button>
                <a input class="btn btn-primary" type="submit" role="button" onclick='history.back()'>취소</a>
 
            </div>
        </div>
    </form>
    
</div>
<script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
</body>

</html>